### ISSUE TITLE
The python script to extract json from pdf data is a mess - should it be refactored? Alternative libraries?

### ISSUE THREAD

**Issue by yedhink** [yedhink/covid19-kerala-api#2]
Currently the script works pretty well. But since the pdfs that we get from dhs kerala is very inconsistent, I had to use a lot of hacks to make the script work as intended. Also the pdftotext library used, is not very effective to all pdfs(say example pdf of date 02/12/2020). So what are your thoughts on refactoring the whole script? What other alternative libraries are there to extract tabular data from pdfs in a much better way? Also just manually adding the data for missing dates is the only solution(which destroys the purpose of this repo, but sitll)?

**Comment by sreehari1997** [comment]
Camelot is an awesome library to extract tabular data from pdf. Camelot is built on top of pdfminer and it works well in most of the cases.
https://camelot-py.readthedocs.io/en/master/
What makes camelot different from others libraries are
- each table is extracted as a pandas dataframe which will make the post extraction processes very easy
- we can control the extraction using lot of parameter

**Comment by yedhink** [comment]
@sreehari1997 Currently the repo uses 'pdftotext' for text extraction from the tables and have lots of caveats. Camelot is an amazing suggestion. I tried it out. But:-

-  Text from some of the pdf files are not extracted properly. For example check [this pdf from 10-03-2020](http://dhs.kerala.gov.in/wp-content/uploads/2020/03/bule_10032020.pdf). Neither pdftotext nor camelot has been able to extract the table in page 3. I tried both the Lattice and Stream flavor with no positive results.

On the plus side, annex2 table has been extracted out pretty neatly.
```
             0                  1                                                  2               3                4
0         Date  No. of \npatients                                           District  Present Status          Remarks
1                               3                    Thrissur \nAlappuzha \nKasargod        Negative       Discharged
2    9.03.2020                  5                                     Pathanamthitta        Negative       Discharged
3    9.03.2020                  1                          Ernakulam (Kannur native)        Negative       Discharged
4   10.03.2020                  8  Kottayam-2 \nPathanamthitta –3 \nErnakulam -2 ...        Negative                 
5                                                                  Pathanamthitta– 1        Positive  Under treatment
```

I'll tweak more on this.
