### ISSUE TITLE
Add option to run python script on an arbitrary pdf file of choice passed as cmd line arg

### ISSUE THREAD

**Issue by yedhink** [yedhink/covid19-kerala-api#4]
Small refactoring of the code would be a necessity i think. Currently since the scripts 'js' variable is populated using the json already existing in data/data.json, the arbitrary file cant have a filename which resembles(eg:- 04-05-2020.pdf or 27-03-2020.pdf) dates/timestamps existing as part of the data.json. That also needs to be fixed.

**Comment by RandallWert** [comment]
Is this still an open issue to be worked on? If so, I might be interested. I would just need some details, of course.

**Comment by yedhink** [comment]
@RandallWert 

Thank you for showing interest in contributing.

Sadly, I don't maintain this repo anymore given that the data source and the format of the PDFs they provide have been widely changed, and it requires a lot of rewriting of the core logic to parse data.

I'm closing this issue and will mark the repo as deperecated.

Once again, thanks for willing to help.
